### ISSUE TITLE
WebGL console errors when activated multiple times

### ISSUE THREAD

**Issue by cvn** [m1el/woscope#4]
When using woscope in a single page app context, the console is spammed with OpenGL error messages if woscope is activated more than once e.g. `WebGL: INVALID_OPERATION: bindBuffer: object not from this context`. Woscope still works, but it'd be better without the errors.

**Comment by m1el** [comment]
These issues happened due to global variables being reused by several instances of the renderer.

Several instances of the renderer now (hopefully) don't interfere with each other.
