### ISSUE TITLE
Afterglow: why uvl.w/2048.0

### ISSUE THREAD

**Issue by nnmm** [m1el/woscope#8]
Hi,
I'm trying to port woscope to a native Rust application and would like to ask a question regarding the fragment shader.

The afterglow coefficient is `smoothstep(0.0, 0.33, uvl.w/2048.0)`, but `uvl.w` is `floor(aIdx / 4.0 + 0.5)`, so between 0 and 1. That makes the afterglow coefficient basically 0, no? I am puzzled by why it still displays right in woscope, but it makes the line disappear in my application, as expected. What is the reason for this smoothstep expression?

Also, are the `aIdx` indices floats instead of ints because of JS?

**Comment by m1el** [comment]
`floor(aIdx / 4.0 + 0.5)`

`aIdx` is an integer index (stored in float) that grows from 0, thus `uvl.w / 2048.0` can have values from 0 to 1 if you have 2048 points.

**Comment by m1el** [comment]
> Also, are the `aIdx` indices floats instead of ints because of JS?

Yes...

> What is the reason for this smoothstep expression?

The reason for smoothstep here is to emulate the trail fade-out, instead of having uniform intensity.
I didn't do any rigorous calculations to do this properly, but it is still visually more pleasing than not doing anything.

![.](http://i.imgur.com/Y9Hubdd.png)

**Comment by nnmm** [comment]
Thank you for your replies! My mistake was not reading the code that calls the shader closely enough, I had just set `aIdx` directly to values in [0, 1, 2, 3] for all vertices and did away with the `mod`. Is the tail overlapping with the previous frame's non-tail section, i.e. are you rendering some vertices twice?

**Comment by m1el** [comment]
> Is the tail overlapping with the previous frame's non-tail section, i.e. are you rendering some vertices twice?

If you're asking if I'm rendering some points on multiple frames, then yes.

I render 2048 points, and a 44KHz waveform is producing ~733 points per frame, so I render each point approximately three times.

**Comment by m1el** [comment]
I'm closing the issue.

If you have further questions or need some help, please contact me via email.
